### ISSUE TITLE
Some inline tags have a fixed size, irrespective of their container's font size

### ISSUE THREAD

**Issue by pbarney** [tarunjana/simplify#1]
**Version:** latest as of 2022-02-16 of both simple.css and simple-v1.css

**Problem:** Some inline tags have a fixed size, irrespective of their container or context, including `<code>`,`<pre>`,`<kbd>`, and `<samp>`

**Example:** https://jsfiddle.net/pbarney/kL7a3b8m/1/

Content in `<code>` tag is significantly smaller than the rest of the text in the H1 element.

**Suggested solution:** perhaps use `em` rather than `rem` on those inline tags?

**Comment by tarunjana** [comment]
Thanks for reporting this :)

I've just checked your `<h1>Heading <code>code</code></h1>` example and the `<code>` tag is rendered smaller than its parent. I think this is an issue with [simple.css](https://simplecss.org).

Anyway, you can always customize the theme by creating a `css` file in `static` directory and linking the `css` file using [this](https://github.com/tarunjana/simplify/wiki#custom-head) method.
